services:
  kali: 
    build: 
      context: kali/
      args:
        KALI_VERSION: latest
    hostname: kali
    container_name: kali
    volumes:
      - type: bind
        source: ./volume
        target: /share
    networks:
      - kali-network

networks:
  kali-network:
    driver: bridge